# Generated by Django 4.2.15 on 2024-09-06 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanswer',
            name='status',
            field=models.BooleanField(default=True, verbose_name='status'),
        ),
    ]
