# Generated by Django 4.2.15 on 2025-02-08 15:02

from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_alter_blog_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ('-date_updated',), 'verbose_name': 'وبلاگ', 'verbose_name_plural': 'وبلاگ\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='blogcomment',
            options={'ordering': ('-date_created',), 'verbose_name': 'نظر وبلاگ', 'verbose_name_plural': 'نظرات وبلاگ'},
        ),
        migrations.AlterField(
            model_name='blog',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده در'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='به\u200cروزرسانی شده در'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='توضیحات وبلاگ'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='enable_comments',
            field=models.BooleanField(default=True, verbose_name='فعال کردن نظرات در پست'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='img',
            field=models.ImageField(upload_to='blogs/%Y/%m/%d', verbose_name='تصویر اصلی وبلاگ'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('p', 'منتشر شده'), ('r', 'رد شده')], default='p', max_length=1, verbose_name='وضعیت وبلاگ'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=400, verbose_name='عنوان وبلاگ'),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blogs.blog', verbose_name='نظرات وبلاگ'),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده در'),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blogs.blogcomment', verbose_name='والد'),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='status',
            field=models.BooleanField(default=True, help_text='اگر نظر مناسب نیست، آن را به نادرست تنظیم کنید.', verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='text',
            field=models.CharField(max_length=500, verbose_name='متن نظر'),
        ),
    ]
