# Generated by Django 4.2.15 on 2025-03-12 21:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogs', '0007_alter_blog_date_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcomment',
            options={'ordering': ('-date_created',), 'verbose_name': 'نظر وبلاگ', 'verbose_name_plural': 'کامنت وبلاگ'},
        ),
        migrations.AlterField(
            model_name='blog',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='enable_comments',
            field=models.BooleanField(default=True, verbose_name='فعال کردن کامنت در پست'),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_blogs_comments', to=settings.AUTH_USER_MODEL, verbose_name="Comment's author"),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blogs.blog', verbose_name='کامنت\u200cهای وبلاگ'),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='text',
            field=models.CharField(max_length=500, verbose_name='متن کامنت'),
        ),
    ]
