# Generated by Django 4.2.15 on 2025-03-25 23:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0016_alter_instructor_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogs', '0008_alter_blogcomment_options_alter_blog_date_created_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ('-date_updated',), 'verbose_name': 'Blog', 'verbose_name_plural': 'Blogs'},
        ),
        migrations.AlterModelOptions(
            name='blogcomment',
            options={'ordering': ('-date_created',), 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='instructors.instructor', verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='enable_comments',
            field=models.BooleanField(default=True, help_text='If checked, users will be able to post comments on this content.', verbose_name='Enable comments'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='img',
            field=models.ImageField(upload_to='blogs/%Y/%m/%d', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('p', 'Published'), ('r', 'Rejected')], default='p', max_length=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=400, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_blogs_comments', to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blogs.blog', verbose_name='Blog'),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blogs.blogcomment', verbose_name='Replayed to'),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='status',
            field=models.BooleanField(default=True, help_text='If the comment is not appropriate, set it to false.', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='text',
            field=models.CharField(max_length=500, verbose_name='Text'),
        ),
    ]
