# Generated by Django 4.2.15 on 2024-09-06 23:28

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonenumber', models.CharField(blank=True, max_length=11, null=True, verbose_name='Phone number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email address')),
                ('adress', django_ckeditor_5.fields.CKEditor5Field(blank=True, max_length=255, null=True, verbose_name='Adress')),
            ],
        ),
    ]
