# Generated by Django 4.2.15 on 2024-09-06 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='Is primary'),
            preserve_default=False,
        ),
    ]
