# Generated by Django 4.2.15 on 2024-09-07 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_contactinfo_is_primary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='is_primary',
            field=models.BooleanField(verbose_name='Is primary?!'),
        ),
    ]
