# Generated by Django 4.2.15 on 2024-09-08 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_alter_contactinfo_is_primary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='phonenumber',
            field=models.CharField(default=1, max_length=11, verbose_name='Phone number'),
            preserve_default=False,
        ),
    ]
