# Generated by Django 4.2.15 on 2024-09-08 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_alter_contactinfo_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='is_primary',
            field=models.BooleanField(help_text='you can only have 1 primary contact', verbose_name='Is primary'),
        ),
    ]
