version: '3.9'

services:
  web:
    build: .
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - static-volume:/src/staticfiles
      - media-volume:/src/media
    container_name: fastball-web-container
    env_file:
      - .env
    restart: unless-stopped

  db:
    image: mysql:8.0
    volumes:
      - mysql-data:/var/lib/mysql
    env_file:
      - .env
    ports:
      - "3306:3306"
    container_name: fastball-mysql-container
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  nginx:
    build: ./nginx
    container_name: fastball-nginx-container
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static-volume:/src/staticfiles
      - media-volume:/src/media
      - /etc/letsencrypt:/etc/letsencrypt
      - ./certbot-webroot:/var/www/certbot
    depends_on:
      - web
    restart: unless-stopped

volumes:
  mysql-data:
  static-volume:
  media-volume: