version: '3.9'

services:
  web:
    build: .
    volumes:
      - ./src:/src
      - static-volume:/src/staticfiles
      - media-volume:/src/media
    container_name: fastball-web-container
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    restart: unless-stopped

  db:
    image: mysql:8.0
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DEFAULT_AUTHENTICATION_PLUGIN=caching_sha2_password
    ports:
      - "3306:3306"
    container_name: fastball-mysql-container
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  nginx:
    build: ./nginx
    container_name: fastball-nginx-container
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static-volume:/usr/share/nginx/html/staticfiles
      - media-volume:/usr/share/nginx/html/media
      - ./nginx/certs:/etc/nginx/certs
    depends_on:
      - web
    restart: unless-stopped

volumes:
  mysql-data:
  static-volume:
  media-volume: