apps:
  - id: "django-app"
    name: "fastball-test"
    image: "python:3.9-slim"
    bundlePlanID: "standard"
    planID: "small-g2"
    port: 8000
    envs:
      PYTHONDONTWRITEBYTECODE: "1"
      PYTHONUNBUFFERED: "1"
      DEBIAN_FRONTEND: "noninteractive"
      DATABASE_URL: mysql://$DB_main_USER:$DB_main_PASSWORD@$DB_main_HOST:$DB_main_PORT/$DB_main_NAME/DB_NAME:$DB_main_NAME
      DB_USER: "$DB_main_USER"
      DB_PASSWORD: "$DB_main_PASSWORD"
      DB_HOST: "$DB_main_HOST"
      DB_PORT: "$DB_main_PORT"
      SECRET_KEY: "${SECRET_KEY}"
    disks:
      - name: "media-volume"
        mountTo: "/src/media"
        size: 3
      - name: "src"
        mountTo: "/src"
        size: 1
      - name: "static-volume"
        mountTo: "/src/staticfiles"
        size: 1
    args:
      - sh 
      - python manage.py migrate
      - python manage.py runserver 0.0.0.0:8000
      - python manage.py collectstatic --noinput
      -

databases:
  - type: "mysql"
    id: "main"
    version: "9.0.1"
    bundlePlanID: "standard"
    planID: "small-g2"