# Generated by Django 4.2.15 on 2025-02-08 15:02

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0002_questionanswer_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionanswer',
            options={'ordering': ('date_modified',), 'verbose_name': 'سوال و جواب', 'verbose_name_plural': 'سوالات و جواب ها'},
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='answer',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='جواب'),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش'),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='question',
            field=models.CharField(max_length=150, verbose_name='سوال'),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='slug',
            field=models.SlugField(verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='status',
            field=models.BooleanField(default=True, verbose_name='وضعیت'),
        ),
    ]
