# Generated by Django 4.2.15 on 2025-03-25 23:01

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0003_alter_questionanswer_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionanswer',
            options={'ordering': ('date_modified',), 'verbose_name': 'question and answer', 'verbose_name_plural': 'questions and answers'},
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='answer',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='answer'),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='date modified'),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='question',
            field=models.CharField(max_length=150, verbose_name='question'),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='slug',
            field=models.SlugField(verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='status',
            field=models.BooleanField(default=True, verbose_name='status'),
        ),
    ]
