# Generated by Django 4.2.15 on 2024-09-05 01:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400, verbose_name="Blog's title")),
                ('slug', models.SlugField()),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name="blog's description")),
                ('img', models.ImageField(upload_to='blogs/%Y/%m/%d', verbose_name="Blog's main img")),
                ('status', models.CharField(choices=[('p', 'Published'), ('r', 'Rejected')], default='p', max_length=1, verbose_name="Blog's status")),
                ('enable_comments', models.BooleanField(default=True, verbose_name='Enable comments on post')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
                'ordering': ('-date_updated',),
            },
        ),
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name="Comment's text")),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_blogs_comments', to=settings.AUTH_USER_MODEL, verbose_name="Blog's author")),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blogs.blog', verbose_name="Blog's comments")),
            ],
            options={
                'verbose_name': 'Blog comment',
                'verbose_name_plural': 'Blog comments',
                'ordering': ('-date_created',),
            },
        ),
    ]
