# Generated by Django 4.2.15 on 2024-09-06 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blogs.blogcomment', verbose_name='Parent'),
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='status',
            field=models.BooleanField(default=True, help_text='If the comment is not appropriate, set it to false.', verbose_name='Status'),
        ),
    ]
