# Generated by Django 4.2.15 on 2024-09-06 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_delete_courseoptions'),
        ('blogs', '0002_blogcomment_parent_blogcomment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='courses.instructor'),
        ),
    ]
