# Generated by Django 4.2.15 on 2025-02-14 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ('date_updated', '-date_created'), 'verbose_name': 'Ticket', 'verbose_name_plural': 'Tickets'},
        ),
        migrations.RemoveIndex(
            model_name='ticket',
            name='date_idx',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='resolved_date',
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['date_updated', 'date_created'], name='date_idx'),
        ),
    ]
