# Generated by Django 4.2.15 on 2025-02-14 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_ticket_options_remove_ticket_date_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ('-date_updated', '-date_created'), 'verbose_name': 'Ticket', 'verbose_name_plural': 'Tickets'},
        ),
        migrations.AlterModelOptions(
            name='ticketreply',
            options={'ordering': ('-date_created',), 'verbose_name': 'Reply', 'verbose_name_plural': 'Replies'},
        ),
    ]
