# Generated by Django 4.2.15 on 2024-10-16 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0010_remove_instructor_status_instructor_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='is_master',
            field=models.BooleanField(default=False, help_text='Check this box to set master instructor and display social media links.', verbose_name='is master'),
        ),
    ]
