# Generated by Django 4.2.15 on 2024-10-16 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0012_alter_instructor_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructor',
            old_name='exprience',
            new_name='experience',
        ),
    ]
