# Generated by Django 4.2.15 on 2025-02-08 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instructors', '0013_rename_exprience_instructor_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='description',
            field=models.TextField(help_text='توضیحات دقیقی از مدرس ارائه دهید.', verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='experience',
            field=models.PositiveIntegerField(help_text='تعداد سال\u200cهای تجربه را وارد کنید.', verbose_name='تجربه'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='instagram_id',
            field=models.CharField(blank=True, help_text='شناسه اینستاگرام خود را برای نمایش در پروفایل وارد کنید.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='is_active',
            field=models.BooleanField(default=True, help_text='این کادر را علامت بزنید تا این مدرس به عنوان فعال تنظیم شود.', verbose_name='آیا فعال است'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='is_master',
            field=models.BooleanField(default=False, help_text='این کادر را علامت بزنید تا مدرس اصلی شود و لینک\u200cهای شبکه\u200cهای اجتماعی نمایش داده شود.', verbose_name='آیا استاد است'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='telegram_id',
            field=models.CharField(blank=True, help_text='شناسه تلگرام خود را برای نمایش در پروفایل وارد کنید.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='youtube_id',
            field=models.CharField(blank=True, help_text='شناسه یوتیوب خود را برای نمایش در پروفایل وارد کنید.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='instructorhonor',
            name='img',
            field=models.ImageField(upload_to='instructors/honor/img', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='instructorhonor',
            name='instructor',
            field=models.ForeignKey(help_text='افتخارات خود را اینجا اضافه کنید، با یک عکس مرتبط', on_delete=django.db.models.deletion.CASCADE, related_name='honors', to='instructors.instructor', verbose_name='مدرس'),
        ),
        migrations.AlterField(
            model_name='instructorhonor',
            name='status',
            field=models.BooleanField(default=True, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='instructorhonor',
            name='text',
            field=models.CharField(max_length=50, verbose_name='افتخار'),
        ),
        migrations.AlterField(
            model_name='instructorwidjet',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widjets', to='instructors.instructor', verbose_name='ویجت مدرس'),
        ),
        migrations.AlterField(
            model_name='instructorwidjet',
            name='widjet',
            field=models.CharField(help_text='ویجت کوتاه', max_length=20, verbose_name='ویجت'),
        ),
    ]
