# Generated by Django 4.2.15 on 2025-03-25 23:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instructors', '0015_remove_instructor_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instructor',
            options={'verbose_name': 'Coach', 'verbose_name_plural': 'Coaches'},
        ),
        migrations.AlterModelOptions(
            name='instructorhonor',
            options={'verbose_name': 'Honor', 'verbose_name_plural': 'Honors'},
        ),
        migrations.AlterModelOptions(
            name='instructorwidjet',
            options={'verbose_name': 'widjet', 'verbose_name_plural': 'widjets'},
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='instagram_id',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='is_master',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='telegram_id',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='youtube_id',
        ),
        migrations.AlterField(
            model_name='instructor',
            name='description',
            field=models.TextField(help_text='Provide a detailed description of the instructor.', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='experience',
            field=models.PositiveIntegerField(help_text='Enter the number of years of experience.', verbose_name='experience'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Check this box to set this instructor as active.', verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='instructorhonor',
            name='img',
            field=models.ImageField(upload_to='instructors/honor/img', verbose_name='photo'),
        ),
        migrations.AlterField(
            model_name='instructorhonor',
            name='instructor',
            field=models.ForeignKey(help_text='add your honor here, with one related photo', on_delete=django.db.models.deletion.CASCADE, related_name='honors', to='instructors.instructor', verbose_name='coach'),
        ),
        migrations.AlterField(
            model_name='instructorhonor',
            name='status',
            field=models.BooleanField(default=True, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='instructorhonor',
            name='text',
            field=models.CharField(max_length=50, verbose_name='honor'),
        ),
        migrations.AlterField(
            model_name='instructorwidjet',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widjets', to='instructors.instructor', verbose_name='instructor widjet'),
        ),
        migrations.AlterField(
            model_name='instructorwidjet',
            name='widjet',
            field=models.CharField(help_text='short Widjet', max_length=20, verbose_name='widjet'),
        ),
    ]
