# Generated by Django 4.2.15 on 2024-08-21 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date_valid_from', models.DateField()),
                ('date_valid_to', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('max_usage_per_user', models.IntegerField(default=1)),
            ],
        ),
    ]
