# Generated by Django 4.2.15 on 2024-08-21 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_coupon_active_coupon_status_alter_coupon_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='certificate_status',
            field=models.BooleanField(default=1, help_text='Show that this course have certificate or no.', verbose_name='certificate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.CharField(default=1, help_text='How long it takes to complete this course?.', max_length=10, verbose_name='duration'),
            preserve_default=False,
        ),
    ]
