# Generated by Django 4.2.15 on 2024-08-23 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_certificate_status_course_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='discount_coupon',
        ),
    ]
