# Generated by Django 4.2.15 on 2024-08-26 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_coursevideos_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseVideos',
            new_name='CourseVideo',
        ),
    ]
