# Generated by Django 4.2.15 on 2024-08-31 22:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0013_vippackagemembership'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coursemembership',
            unique_together={('user', 'course')},
        ),
    ]
