# Generated by Django 4.2.15 on 2024-09-03 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_coursecomments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursecomments',
            options={'ordering': ('-date_created',)},
        ),
        migrations.AddField(
            model_name='coursecomments',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='courses.coursecomments', verbose_name='Parent'),
        ),
    ]
