# Generated by Django 4.2.15 on 2024-09-04 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_alter_course_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='parent',
            field=models.ManyToManyField(blank=True, to='courses.course', verbose_name='Courses'),
        ),
    ]
