# Generated by Django 4.2.15 on 2024-09-04 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_alter_course_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='options',
        ),
        migrations.AddField(
            model_name='course',
            name='analysis_room_status',
            field=models.BooleanField(default=False, verbose_name='analysis room'),
        ),
        migrations.AddField(
            model_name='course',
            name='certificate_status',
            field=models.BooleanField(default=False, help_text='Show that this course have certificate or no.', verbose_name='certificate'),
        ),
        migrations.AddField(
            model_name='course',
            name='extra_movments_status',
            field=models.BooleanField(default=False, verbose_name='extra movments'),
        ),
        migrations.AddField(
            model_name='course',
            name='injury_prevention_status',
            field=models.BooleanField(default=False, verbose_name='injury prevention'),
        ),
    ]
