# Generated by Django 4.2.15 on 2024-09-08 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0026_instructor_exprience_instructor_telegram_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='instagram_id',
            field=models.CharField(default=1, help_text='Your instagram id for showing in your profile!', max_length=50),
            preserve_default=False,
        ),
    ]
