# Generated by Django 4.2.15 on 2024-09-08 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0028_instructorwidjet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructorwidjet',
            name='widjet',
            field=models.CharField(help_text='short Widjet', max_length=20, verbose_name='widjet'),
        ),
    ]
