# Generated by Django 4.2.15 on 2024-09-09 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_alter_blog_author'),
        ('instructors', '0001_initial'),
        ('courses', '0029_alter_instructorwidjet_widjet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructorwidjet',
            name='instructor',
        ),
        migrations.AlterField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='instructors.instructor', verbose_name='instructor'),
        ),
        migrations.DeleteModel(
            name='Instructor',
        ),
        migrations.DeleteModel(
            name='InstructorWidjet',
        ),
    ]
