# Generated by Django 4.2.15 on 2024-09-09 00:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='description of instructor')),
                ('exprience', models.PositiveIntegerField(help_text='How many years of experience do you have?!', verbose_name='exprience')),
                ('telegram_id', models.CharField(help_text='Your telegram id for showing in your profile!', max_length=50)),
                ('youtube_id', models.CharField(help_text='Your youtube id for showing in your profile!', max_length=50)),
                ('instagram_id', models.CharField(help_text='Your instagram id for showing in your profile!', max_length=50)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.CreateModel(
            name='InstructorWidjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widjet', models.CharField(help_text='short Widjet', max_length=20, verbose_name='widjet')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widjets', to='instructors.instructor', verbose_name='instructor widjet')),
            ],
        ),
    ]
