# Generated by Django 4.2.15 on 2024-09-09 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='instagram_id',
            field=models.CharField(blank=True, help_text='Your instagram id for showing in your profile!', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='telegram_id',
            field=models.CharField(blank=True, help_text='Your telegram id for showing in your profile!', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='youtube_id',
            field=models.CharField(blank=True, help_text='Your youtube id for showing in your profile!', max_length=50, null=True),
        ),
    ]
