# Generated by Django 4.2.15 on 2024-09-09 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0002_alter_instructor_instagram_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
