# Generated by Django 4.2.15 on 2024-09-09 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0004_instructor_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='img',
            field=models.ImageField(default=1, upload_to='instructors/imgs/'),
            preserve_default=False,
        ),
    ]
