# Generated by Django 4.2.15 on 2024-09-09 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0006_alter_instructor_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorHonor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('honor', models.CharField(max_length=50, verbose_name='honor')),
                ('img', models.ImageField(upload_to='instructors/honor/img', verbose_name='photo')),
                ('status', models.BooleanField(default=True, verbose_name='status')),
                ('instructor', models.ForeignKey(help_text='add your honor here, with one related photo', on_delete=django.db.models.deletion.CASCADE, related_name='honors', to='instructors.instructor', verbose_name='instructor')),
            ],
        ),
    ]
