# Generated by Django 4.2.15 on 2024-10-16 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0009_alter_instructor_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='status',
        ),
        migrations.AddField(
            model_name='instructor',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is active'),
        ),
    ]
