# Generated by Django 4.2.15 on 2024-10-16 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0011_instructor_is_master'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='description',
            field=models.TextField(help_text='Provide a detailed description of the instructor.', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='exprience',
            field=models.PositiveIntegerField(help_text='Enter the number of years of experience.', verbose_name='experience'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='instagram_id',
            field=models.CharField(blank=True, help_text='Enter your Instagram ID to display on your profile.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Check this box to set this instructor as active.', verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='telegram_id',
            field=models.CharField(blank=True, help_text='Enter your Telegram ID to display on your profile.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='youtube_id',
            field=models.CharField(blank=True, help_text='Enter your YouTube ID to display on your profile.', max_length=50, null=True),
        ),
    ]
