FROM nginx:alpine

RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/nginx.conf

RUN mkdir -p /usr/share/nginx/html/staticfiles
RUN mkdir -p /usr/share/nginx/html/media

COPY ./certs /etc/nginx/certs
