# Generated by Django 4.2.15 on 2024-08-21 11:30

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='1', max_length=128, region='IR', verbose_name='Phone number'),
            preserve_default=False,
        ),
    ]
