# Generated by Django 4.2.15 on 2024-10-05 19:24

import apps.accounts.models
from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_managers_remove_customuser_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='IR', unique=True, validators=[apps.accounts.models.phone_number_validator_for_iran], verbose_name='phonenumber'),
        ),
    ]
