# Generated by Django 4.2.15 on 2025-02-11 23:40

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.accounts.models.upload_user_profle_photo_path),
        ),
    ]
