# Generated by Django 4.2.15 on 2025-02-13 23:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='Subject')),
                ('message', models.TextField(verbose_name='پیام')),
                ('status', models.CharField(choices=[('p', 'در انتظار'), ('r', 'Resolved'), ('c', 'Closed')], default='p', max_length=1, verbose_name='وضعیت')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
                ('resolved_date', models.DateTimeField(blank=True, null=True, verbose_name='Resolved Date')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ('resolved_date', '-date_created'),
                'indexes': [models.Index(fields=['resolved_date', 'date_created'], name='date_idx'), models.Index(fields=['user'], name='user_idx')],
            },
        ),
    ]
