# Generated by Django 4.2.15 on 2025-02-13 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='پیام')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='accounts.ticket', verbose_name='Ticket')),
            ],
            options={
                'verbose_name': 'پاسخ',
                'verbose_name_plural': 'Replies',
                'ordering': ('date_created',),
                'indexes': [models.Index(fields=['ticket'], name='replies_ticket_idx'), models.Index(fields=['date_created'], name='replies_date_idx')],
            },
        ),
    ]
