# Generated by Django 4.2.15 on 2025-02-13 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_ticketreply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketreply',
            name='ticket',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
        migrations.DeleteModel(
            name='TicketReply',
        ),
    ]
