# Generated by Django 4.2.15 on 2025-03-25 23:01

import apps.accounts.models
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_ticketreply_ticket_delete_ticket_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Bio'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='IR', unique=True, validators=[apps.accounts.models.phone_number_validator_for_iran], verbose_name='Phonenumber'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.accounts.models.upload_user_profle_photo_path, verbose_name='Profile Photo'),
        ),
    ]
