# Generated by Django 4.2.15 on 2024-08-21 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0002_instructor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='active',
        ),
        migrations.AddField(
            model_name='coupon',
            name='status',
            field=models.BooleanField(default=True, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='code of coupon'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='date_valid_from',
            field=models.DateField(verbose_name='date valid from'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='date_valid_to',
            field=models.DateField(verbose_name='date valid to'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='discount amount'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='max_usage_per_user',
            field=models.IntegerField(default=1, help_text='Number of people who can use.', verbose_name='max number of usage'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='description',
            field=models.TextField(verbose_name='description of instructor'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('age_range', models.CharField(help_text='Age range for users.', max_length=50, verbose_name='age range')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Discount amount for course.', max_digits=5, verbose_name='discount amount')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created at')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='date modified at')),
                ('status', models.BooleanField(default=True, help_text='Show that this course is active or no.', verbose_name='status')),
                ('discount_coupon', models.ForeignKey(blank=True, help_text='Discount with coupon', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.coupon', verbose_name='discount coupon')),
                ('instructor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.instructor', verbose_name='instructor')),
            ],
        ),
    ]
