# Generated by Django 4.2.15 on 2024-08-26 00:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_rename_coursevideos_coursevideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vippackage',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coursevideo',
            name='status',
            field=models.CharField(choices=[('m', 'Monetary'), ('f', 'Free')], default='m', help_text='Show that this video is free or not.', max_length=1, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='coursevideo',
            name='video',
            field=models.FileField(blank=True, help_text='Valid video formats: mp4, mkv, wmv, 3gp, f4v, avi, mp3', null=True, upload_to='course_videos', validators=[django.core.validators.FileExtensionValidator(['mp4', 'mkv', 'wmv', '3gp', 'f4v', 'avi', 'mp3'])], verbose_name='Course video'),
        ),
    ]
