# Generated by Django 4.2.15 on 2024-09-04 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_alter_coursecomments_options_coursecomments_parent'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vippackagemembership',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='vippackagemembership',
            name='user',
        ),
        migrations.RemoveField(
            model_name='vippackagemembership',
            name='vip_package',
        ),
        migrations.AddField(
            model_name='course',
            name='parent',
            field=models.ManyToManyField(null=True, related_name='packages', to='courses.course', verbose_name='Courses'),
        ),
        migrations.DeleteModel(
            name='VipPackage',
        ),
        migrations.DeleteModel(
            name='VipPackageMembership',
        ),
    ]
