# Generated by Django 4.2.15 on 2024-09-04 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_course_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='options',
            field=models.ManyToManyField(blank=True, to='courses.courseoptions', verbose_name='Options'),
        ),
    ]
