# Generated by Django 4.2.15 on 2025-01-30 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0031_course_img_alter_course_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(allow_unicode=True, unique=True),
        ),
    ]
