# Generated by Django 4.2.15 on 2025-02-08 15:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instructors', '0014_alter_instructor_description_and_more'),
        ('courses', '0032_alter_course_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='کد کوپن'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='date_valid_from',
            field=models.DateField(verbose_name='تاریخ اعتبار از'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='date_valid_to',
            field=models.DateField(verbose_name='تاریخ اعتبار تا'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='مقدار تخفیف'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='max_usage_per_user',
            field=models.IntegerField(default=1, help_text='Number of people who can use.', verbose_name='حداکثر تعداد استفاده'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='status',
            field=models.BooleanField(default=True, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='course',
            name='age_range',
            field=models.CharField(help_text='محدوده سنی برای کاربران.', max_length=50, verbose_name='محدوده سنی'),
        ),
        migrations.AlterField(
            model_name='course',
            name='analysis_room_status',
            field=models.BooleanField(default=False, verbose_name='اتاق تحلیل'),
        ),
        migrations.AlterField(
            model_name='course',
            name='certificate_status',
            field=models.BooleanField(default=False, help_text='Show that this course have certificate or no.', verbose_name='گواهی'),
        ),
        migrations.AlterField(
            model_name='course',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد در'),
        ),
        migrations.AlterField(
            model_name='course',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش در'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='course',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='مقدار تخفیف برای دوره.', max_digits=5, verbose_name='مقدار تخفیف'),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.CharField(help_text='مدت زمان لازم برای اتمام این دوره چقدر است؟', max_length=10, verbose_name='مدت زمان'),
        ),
        migrations.AlterField(
            model_name='course',
            name='extra_movments_status',
            field=models.BooleanField(default=False, verbose_name='حرکات اضافی'),
        ),
        migrations.AlterField(
            model_name='course',
            name='img',
            field=models.ImageField(upload_to='courses/%Y/%m/%d', verbose_name='تصویر اصلی'),
        ),
        migrations.AlterField(
            model_name='course',
            name='injury_prevention_status',
            field=models.BooleanField(default=False, verbose_name='پیشگیری از آسیب'),
        ),
        migrations.AlterField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='instructors.instructor', verbose_name='مدرس'),
        ),
        migrations.AlterField(
            model_name='course',
            name='parent',
            field=models.ManyToManyField(blank=True, to='courses.course', verbose_name='دوره\u200cها'),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.BooleanField(default=True, help_text='Show that this course is active or no.', verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=100, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='coursecomments',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='courses.course', verbose_name='دوره'),
        ),
        migrations.AlterField(
            model_name='coursecomments',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='coursecomments',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='courses.coursecomments', verbose_name='والد'),
        ),
        migrations.AlterField(
            model_name='coursecomments',
            name='status',
            field=models.BooleanField(default=True, help_text='اگر نظر مناسب نیست، آن را به نادرست تنظیم کنید.', verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='coursecomments',
            name='text',
            field=models.TextField(verbose_name='متن نظر'),
        ),
        migrations.AlterField(
            model_name='coursecomments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_comments', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='coursemembership',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='courses.course', verbose_name='دوره'),
        ),
        migrations.AlterField(
            model_name='coursemembership',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='coursemembership',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش'),
        ),
        migrations.AlterField(
            model_name='coursemembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL, verbose_name='عضویت در دوره'),
        ),
        migrations.AlterField(
            model_name='coursevideo',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='courses.course', verbose_name='دوره'),
        ),
        migrations.AlterField(
            model_name='coursevideo',
            name='status',
            field=models.CharField(choices=[('m', 'پولی'), ('f', 'رایگان')], default='m', help_text='Show that this video is free or not.', max_length=1, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='coursevideo',
            name='title',
            field=models.CharField(max_length=100, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='coursevideo',
            name='video',
            field=models.FileField(help_text='Valid video formats: mp4, mkv, wmv, 3gp, f4v, avi, mp3', upload_to='course_videos', validators=[django.core.validators.FileExtensionValidator(['mp4', 'mkv', 'wmv', '3gp', 'f4v', 'avi', 'mp3'])], verbose_name='ویدیو دوره'),
        ),
        migrations.CreateModel(
            name='CourseLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(verbose_name='تاریخ ایجاد')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='courses.course', verbose_name='دوره')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': "Course's Like",
                'verbose_name_plural': "Course's Likes",
                'ordering': ('-date_created',),
                'indexes': [models.Index(fields=['course'], name='course_like_course_idx'), models.Index(fields=['user'], name='course_like_user_idx'), models.Index(fields=['-date_created'], name='course_like_date_created_idx')],
                'unique_together': {('course', 'user')},
            },
        ),
    ]
