# Generated by Django 4.2.15 on 2025-02-10 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0033_alter_coupon_code_alter_coupon_date_valid_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courselike',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
    ]
