# Generated by Django 4.2.15 on 2025-02-10 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0034_alter_courselike_date_created'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseLike',
        ),
    ]
