# Generated by Django 4.2.15 on 2025-02-10 21:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0035_delete_courselike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursecomments',
            name='parent',
        ),
        migrations.AddField(
            model_name='coursecomments',
            name='rate',
            field=models.PositiveSmallIntegerField(default=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Rate'),
            preserve_default=False,
        ),
    ]
