# Generated by Django 4.2.15 on 2025-02-14 22:18

import apps.courses.models
from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0014_alter_instructor_description_and_more'),
        ('courses', '0037_alter_coursecomments_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='course',
            name='parent',
        ),
        migrations.AddField(
            model_name='course',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='instructors.instructor', verbose_name='Coach'),
        ),
        migrations.AddField(
            model_name='course',
            name='introduce_video',
            field=models.FileField(blank=True, null=True, upload_to=apps.courses.models.upload_introduce_video_path, verbose_name='Introduce Video'),
        ),
        migrations.AlterField(
            model_name='course',
            name='age_range',
            field=models.CharField(help_text='محدوده سنی برای کاربران.', max_length=50, verbose_name='Age range'),
        ),
        migrations.AlterField(
            model_name='course',
            name='analysis_room_status',
            field=models.BooleanField(default=False, verbose_name='Analysis room'),
        ),
        migrations.AlterField(
            model_name='course',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date created at'),
        ),
        migrations.AlterField(
            model_name='course',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Date modified at'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='course',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Discount amount for this product.', max_digits=5, verbose_name='مقدار تخفیف'),
        ),
        migrations.AlterField(
            model_name='course',
            name='extra_movments_status',
            field=models.BooleanField(default=False, verbose_name='Extra movments'),
        ),
        migrations.AlterField(
            model_name='course',
            name='img',
            field=models.ImageField(upload_to=apps.courses.models.upload_introduce_image_path, verbose_name='Main img'),
        ),
        migrations.AlterField(
            model_name='course',
            name='injury_prevention_status',
            field=models.BooleanField(default=False, verbose_name='Injury prevention'),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.BooleanField(default=True, help_text='Show that this product is active or not.', verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Discount amount for this product.', max_digits=5, verbose_name='مقدار تخفیف')),
                ('img', models.ImageField(upload_to=apps.courses.models.upload_introduce_image_path, verbose_name='Main img')),
                ('introduce_video', models.FileField(blank=True, null=True, upload_to=apps.courses.models.upload_introduce_video_path, verbose_name='Introduce Video')),
                ('age_range', models.CharField(help_text='محدوده سنی برای کاربران.', max_length=50, verbose_name='Age range')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created at')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Date modified at')),
                ('status', models.BooleanField(default=True, help_text='Show that this product is active or not.', verbose_name='وضعیت')),
                ('certificate_status', models.BooleanField(default=False, help_text='Show that this course have certificate or no.', verbose_name='گواهی')),
                ('analysis_room_status', models.BooleanField(default=False, verbose_name='Analysis room')),
                ('extra_movments_status', models.BooleanField(default=False, verbose_name='Extra movments')),
                ('injury_prevention_status', models.BooleanField(default=False, verbose_name='Injury prevention')),
                ('courses', models.ManyToManyField(to='courses.course', verbose_name='Courses in this package')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
