# Generated by Django 4.2.15 on 2025-02-15 00:44
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0038_remove_course_instructor_remove_course_parent_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursemembership',
            options={'verbose_name': 'Course Membership', 'verbose_name_plural': 'Course Memberships'},
        ),

        migrations.AlterUniqueTogether(
            name='coursemembership',
            unique_together=set(),
        ),

        migrations.AddField(
            model_name='coursemembership',
            name='content_type',
            field=models.ForeignKey(
                limit_choices_to={'model__in': ('course', 'package')},
                on_delete=django.db.models.deletion.CASCADE,
                to='contenttypes.contenttype',
                verbose_name='Content Type',
            ),
        ),

        migrations.AddField(
            model_name='coursemembership',
            name='object_id',
            field=models.PositiveIntegerField(verbose_name='Object ID'),
        ),

        migrations.AlterField(
            model_name='coursemembership',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Date'),
        ),

        migrations.AlterField(
            model_name='coursemembership',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified Date'),
        ),

        migrations.AlterField(
            model_name='coursemembership',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='memberships',
                to=settings.AUTH_USER_MODEL,
                verbose_name='User Membership',
            ),
        ),

        migrations.AlterUniqueTogether(
            name='coursemembership',
            unique_together={('user', 'content_type', 'object_id')},
        ),

        migrations.RemoveField(
            model_name='coursemembership',
            name='course',
        ),
    ]
