# Generated by Django 4.2.15 on 2025-02-17 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0039_alter_coursemembership_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده در')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='به\u200cروزرسانی شده در')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Seasons', to='courses.course', verbose_name='دوره')),
            ],
            options={
                'verbose_name': 'Season',
                'verbose_name_plural': 'Seasons',
                'ordering': ['created_at'],
            },
        ),
    ]
