# Generated by Django 4.2.15 on 2025-02-17 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0040_courseseason'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseseason',
            options={'ordering': ('created_at',), 'verbose_name': 'Season', 'verbose_name_plural': 'Seasons'},
        ),
    ]
