# Generated by Django 4.2.15 on 2025-02-17 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0042_alter_coursevideo_options_remove_coursevideo_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseseason',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='courses.course', verbose_name='دوره'),
        ),
        migrations.AlterField(
            model_name='coursevideo',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='courses.courseseason', verbose_name='Season'),
        ),
    ]
