# Generated by Django 4.2.15 on 2025-02-21 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0043_alter_courseseason_course_alter_coursevideo_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='duration',
            field=models.CharField(default=12, help_text='مدت زمان لازم برای اتمام این دوره چقدر است؟', max_length=10, verbose_name='مدت زمان'),
            preserve_default=False,
        ),
    ]
