# Generated by Django 4.2.15 on 2025-02-21 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0047_course_introduce_video_cover_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='introduce_video_url',
            field=models.URLField(blank=True, null=True, verbose_name='Introduce Video URL'),
        ),
        migrations.AddField(
            model_name='package',
            name='introduce_video_url',
            field=models.URLField(blank=True, null=True, verbose_name='Introduce Video URL'),
        ),
    ]
