# Generated by Django 4.2.15 on 2025-02-21 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0048_course_introduce_video_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='introduce_video',
        ),
        migrations.RemoveField(
            model_name='package',
            name='introduce_video',
        ),
    ]
