# Generated by Django 4.2.15 on 2025-02-28 10:21

import apps.courses.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0015_remove_instructor_img'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('courses', '0049_remove_course_introduce_video_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursemembership',
            options={'verbose_name': 'عضویت در دوره', 'verbose_name_plural': 'عضویت در دوره\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='courseseason',
            options={'ordering': ('created_at',), 'verbose_name': 'فصل', 'verbose_name_plural': 'فصول'},
        ),
        migrations.AlterModelOptions(
            name='coursevideo',
            options={'ordering': ('created_at',), 'verbose_name': 'ویدیو', 'verbose_name_plural': 'ویدیوها'},
        ),
        migrations.AlterField(
            model_name='course',
            name='age_range',
            field=models.CharField(help_text='محدوده سنی برای کاربران.', max_length=12, verbose_name='محدوده سنی'),
        ),
        migrations.AlterField(
            model_name='course',
            name='analysis_room_status',
            field=models.BooleanField(default=False, verbose_name='اتاق تحلیل'),
        ),
        migrations.AlterField(
            model_name='course',
            name='certificate_status',
            field=models.BooleanField(default=False, help_text='نشان دهید که آیا این دوره گواهی دارد یا خیر.', verbose_name='گواهی'),
        ),
        migrations.AlterField(
            model_name='course',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='instructors.instructor', verbose_name='مربی'),
        ),
        migrations.AlterField(
            model_name='course',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد در'),
        ),
        migrations.AlterField(
            model_name='course',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش در'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='course',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='مقدار تخفیف برای این محصول.', max_digits=5, verbose_name='مقدار تخفیف'),
        ),
        migrations.AlterField(
            model_name='course',
            name='extra_movments_status',
            field=models.BooleanField(default=False, verbose_name='حرکات اضافی'),
        ),
        migrations.AlterField(
            model_name='course',
            name='img',
            field=models.ImageField(upload_to=apps.courses.models.upload_introduce_image_path, verbose_name='تصویر اصلی'),
        ),
        migrations.AlterField(
            model_name='course',
            name='injury_prevention_status',
            field=models.BooleanField(default=False, verbose_name='پیشگیری از آسیب'),
        ),
        migrations.AlterField(
            model_name='course',
            name='introduce_video_cover',
            field=models.ImageField(blank=True, help_text='کاور ویدیو معرفی', null=True, upload_to=apps.courses.models.upload_introduce_video_cover_path, verbose_name='کاور'),
        ),
        migrations.AlterField(
            model_name='course',
            name='introduce_video_url',
            field=models.URLField(blank=True, null=True, verbose_name='آدرس ویدیو معرفی'),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.BooleanField(default=True, help_text='نشان دهید که آیا این محصول فعال است یا خیر.', verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=100, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='coursecomments',
            name='rate',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='امتیاز'),
        ),
        migrations.AlterField(
            model_name='coursemembership',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'model__in': ('course', 'package')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='نوع محتوا'),
        ),
        migrations.AlterField(
            model_name='coursemembership',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='coursemembership',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش'),
        ),
        migrations.AlterField(
            model_name='coursemembership',
            name='object_id',
            field=models.PositiveIntegerField(verbose_name='شناسه شیء'),
        ),
        migrations.AlterField(
            model_name='courseseason',
            name='title',
            field=models.CharField(max_length=100, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='courseseason',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='coursevideo',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='courses.courseseason', verbose_name='فصل'),
        ),
        migrations.AlterField(
            model_name='coursevideo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='package',
            name='age_range',
            field=models.CharField(help_text='محدوده سنی برای کاربران.', max_length=12, verbose_name='محدوده سنی'),
        ),
        migrations.AlterField(
            model_name='package',
            name='analysis_room_status',
            field=models.BooleanField(default=False, verbose_name='اتاق تحلیل'),
        ),
        migrations.AlterField(
            model_name='package',
            name='certificate_status',
            field=models.BooleanField(default=False, help_text='نشان دهید که آیا این دوره گواهی دارد یا خیر.', verbose_name='گواهی'),
        ),
        migrations.AlterField(
            model_name='package',
            name='courses',
            field=models.ManyToManyField(to='courses.course', verbose_name='دوره\u200cهای موجود در این بسته'),
        ),
        migrations.AlterField(
            model_name='package',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد در'),
        ),
        migrations.AlterField(
            model_name='package',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش در'),
        ),
        migrations.AlterField(
            model_name='package',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='package',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='مقدار تخفیف برای این محصول.', max_digits=5, verbose_name='مقدار تخفیف'),
        ),
        migrations.AlterField(
            model_name='package',
            name='extra_movments_status',
            field=models.BooleanField(default=False, verbose_name='حرکات اضافی'),
        ),
        migrations.AlterField(
            model_name='package',
            name='img',
            field=models.ImageField(upload_to=apps.courses.models.upload_introduce_image_path, verbose_name='تصویر اصلی'),
        ),
        migrations.AlterField(
            model_name='package',
            name='injury_prevention_status',
            field=models.BooleanField(default=False, verbose_name='پیشگیری از آسیب'),
        ),
        migrations.AlterField(
            model_name='package',
            name='introduce_video_cover',
            field=models.ImageField(blank=True, help_text='کاور ویدیو معرفی', null=True, upload_to=apps.courses.models.upload_introduce_video_cover_path, verbose_name='کاور'),
        ),
        migrations.AlterField(
            model_name='package',
            name='introduce_video_url',
            field=models.URLField(blank=True, null=True, verbose_name='آدرس ویدیو معرفی'),
        ),
        migrations.AlterField(
            model_name='package',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='package',
            name='status',
            field=models.BooleanField(default=True, help_text='نشان دهید که آیا این محصول فعال است یا خیر.', verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='package',
            name='title',
            field=models.CharField(max_length=100, verbose_name='عنوان'),
        ),
    ]
