# Generated by Django 4.2.15 on 2025-03-13 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0051_alter_coursemembership_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد در'),
        ),
        migrations.AlterField(
            model_name='course',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='تاریخ ویرایش در'),
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.BooleanField(db_index=True, default=True, help_text='نشان دهید که آیا این محصول فعال است یا خیر.', verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(db_index=True, max_length=100, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='package',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد در'),
        ),
        migrations.AlterField(
            model_name='package',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='تاریخ ویرایش در'),
        ),
        migrations.AlterField(
            model_name='package',
            name='status',
            field=models.BooleanField(db_index=True, default=True, help_text='نشان دهید که آیا این محصول فعال است یا خیر.', verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='package',
            name='title',
            field=models.CharField(db_index=True, max_length=100, verbose_name='عنوان'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['status', '-date_created'], name='course_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(condition=models.Q(('status', True), ('discount_amount__gt', 0)), fields=['discount_amount'], name='course_active_discounts_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['coach', 'status'], name='course_coach_status_idx'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['status', '-date_created'], name='package_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(condition=models.Q(('status', True), ('discount_amount__gt', 0)), fields=['discount_amount'], name='package_active_discounts_idx'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['certificate_status', 'status'], name='package_cert_status_idx'),
        ),
    ]
