# Generated by Django 4.2.15 on 2025-03-23 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0053_remove_course_course_active_discounts_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursemembership',
            options={'verbose_name': 'عضو دوره', 'verbose_name_plural': 'عضو دوره'},
        ),
    ]
