# Generated by Django 4.2.15 on 2025-04-03 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0055_alter_coupon_options_alter_course_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='discount_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='Discount amount'),
        ),
        migrations.AlterField(
            model_name='course',
            name='discount_amount',
            field=models.PositiveIntegerField(default=0, help_text='Discount amount for this product.', verbose_name='Discount amount'),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='package',
            name='discount_amount',
            field=models.PositiveIntegerField(default=0, help_text='Discount amount for this product.', verbose_name='Discount amount'),
        ),
        migrations.AlterField(
            model_name='package',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='Price'),
        ),
    ]
