# Generated by Django 4.2.15 on 2025-04-05 10:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0057_telegramlink'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TelegramLink',
            new_name='CourseTelegramLink',
        ),
    ]
