# Generated by Django 4.2.15 on 2025-04-05 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0059_coursetelegramlink_is_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursetelegramlink',
            name='date_update',
        ),
        migrations.AddField(
            model_name='coursetelegramlink',
            name='date_used',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Update Date'),
        ),
    ]
