# Generated by Django 4.2.15 on 2025-04-06 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0060_remove_coursetelegramlink_date_update_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='max_usage_total',
            field=models.IntegerField(default=100, help_text='Maximum number of times the coupon can be used globally.', verbose_name='Max Total Usage'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Coupon Code'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='date_valid_from',
            field=models.DateField(verbose_name='Valid From'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='date_valid_to',
            field=models.DateField(verbose_name='Valid To'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_amount',
            field=models.PositiveIntegerField(default=0, help_text='The amount of discount (in currency units).', verbose_name='Discount Amount'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='max_usage_per_user',
            field=models.IntegerField(default=1, help_text='Maximum number of times a user can use this coupon.', verbose_name='Max Usage Per User'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='status',
            field=models.BooleanField(default=True, help_text='Whether the coupon is active or not.', verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_date', models.DateTimeField(auto_now_add=True, verbose_name='Usage Date')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='courses.coupon', verbose_name='Coupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usages', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Coupon Usage',
                'verbose_name_plural': 'Coupon Usages',
            },
        ),
    ]
