# Generated by Django 4.2.15 on 2025-04-10 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0061_coupon_max_usage_total_alter_coupon_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='free_leasson_link',
            field=models.URLField(blank=True, null=True, unique=True, verbose_name='Free leasson link'),
        ),
    ]
