# Generated by Django 4.2.15 on 2025-04-12 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0062_course_free_leasson_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_featured_on_homepage',
            field=models.BooleanField(default=False, help_text='Only one course can be featured on the homepage at a time.', verbose_name='Featured on Homepage'),
        ),
    ]
