# Generated by Django 4.2.15 on 2025-04-14 07:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0063_course_is_featured_on_homepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(200000000)], verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='package',
            name='price',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(200000000)], verbose_name='Price'),
        ),
    ]
