# Generated by Django 4.2.15 on 2025-03-25 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_alter_contactinfo_options_alter_message_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='is_primary',
            field=models.BooleanField(help_text='You can only have 1 primary contact', verbose_name='Is primary'),
        ),
        migrations.AlterField(
            model_name='message',
            name='date_sent',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Sent Date'),
        ),
    ]
