# Generated by Django 4.2.15 on 2025-03-26 00:19

import apps.orders.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0055_alter_coupon_options_alter_course_options_and_more'),
        ('orders', '0004_dvdorderdetail_city_dvdorderdetail_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dvdorderdetail',
            options={'verbose_name': "DVD's Order", 'verbose_name_plural': "DVD's Orders"},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': "Order's Item", 'verbose_name_plural': "Order's Items"},
        ),
        migrations.AlterField(
            model_name='dvdorderdetail',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='dvdorderdetail',
            name='city',
            field=models.CharField(max_length=15, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='dvdorderdetail',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='dvdorderdetail',
            name='delivery_status',
            field=models.CharField(choices=[('p', 'Pending'), ('s', 'Sent'), ('r', 'Rejected'), ('c', 'Canceled')], default='p', max_length=1, verbose_name='DeliveryStatus'),
        ),
        migrations.AlterField(
            model_name='dvdorderdetail',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='dvdorderdetail',
            name='first_name',
            field=models.CharField(max_length=20, verbose_name='firstName'),
        ),
        migrations.AlterField(
            model_name='dvdorderdetail',
            name='last_name',
            field=models.CharField(max_length=30, verbose_name='LastName'),
        ),
        migrations.AlterField(
            model_name='dvdorderdetail',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dvd_detail', to='orders.order', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='dvdorderdetail',
            name='order_note',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Order'sNote"),
        ),
        migrations.AlterField(
            model_name='dvdorderdetail',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='IR', unique=True, validators=[apps.orders.models.phone_number_validator_for_iran], verbose_name='Phonenumber'),
        ),
        migrations.AlterField(
            model_name='dvdorderdetail',
            name='postal_code',
            field=models.CharField(max_length=20, verbose_name='PostalCode'),
        ),
        migrations.AlterField(
            model_name='order',
            name='access_status',
            field=models.CharField(choices=[('o', 'Online'), ('d', 'DVD')], default='o', max_length=1, verbose_name='AccessStatus'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='DateCreated'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('p', 'Paid'), ('u', 'Unpaid'), ('c', 'Canceled')], default='u', max_length=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='TotalPrice'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='courses.course', verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='orders.order', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='UnitPrice'),
        ),
    ]
