# Generated by Django 4.2.15 on 2025-04-03 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_payment_authority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_authority',
        ),
        migrations.AddField(
            model_name='order',
            name='zarinpal_authority',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Payment Authority'),
        ),
        migrations.AddField(
            model_name='order',
            name='zarinpal_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='zarinpal_ref_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
