# Generated by Django 4.2.15 on 2025-04-03 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_remove_order_payment_authority_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'zarinpal_authority'], name='orders_orde_status_7409f4_idx'),
        ),
    ]
