# Generated by Django 4.2.15 on 2025-04-04 06:09

import apps.orders.models
from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_orders_orde_status_7409f4_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dvdorderdetail',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='IR', validators=[apps.orders.models.phone_number_validator_for_iran], verbose_name='Phonenumber'),
        ),
    ]
