# Generated by Django 4.2.15 on 2025-04-05 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('orders', '0010_alter_dvdorderdetail_phone_number'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='content_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'model__in': ('course', 'package')}, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Content Type'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Object ID'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Unit Price'),
        ),
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('order', 'content_type', 'object_id')},
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='course',
        ),
    ]
