# Generated by Django 4.2.15 on 2025-04-10 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_rename_coupon_order_coupon_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Coupon Code'),
        ),
    ]
