# Generated by Django 4.2.15 on 2025-04-12 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_alter_order_coupon_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dvd_shipping_price', models.PositiveIntegerField(default=0, verbose_name='DVD Shipping Price')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
            ],
            options={
                'verbose_name': 'Shipping Settings',
                'verbose_name_plural': 'Shipping Settings',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='dvd_shipping_price',
            field=models.PositiveIntegerField(default=0, verbose_name='DVD Shipping Price'),
        ),
    ]
