# Generated by Django 4.2.15 on 2025-04-04 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('students', models.IntegerField(default=7000, verbose_name='Students')),
                ('experience_years', models.IntegerField(default=14, verbose_name='Experience years')),
                ('professional_courses', models.IntegerField(default=8, verbose_name='Professional Courses')),
                ('reviews', models.FloatField(default=5, verbose_name='Reviews')),
            ],
            options={
                'verbose_name': 'Counter',
                'verbose_name_plural': 'Counter',
            },
        ),
    ]
